### ISSUE TITLE
Suggestion: Add support for more frameworks(6 & 7)

### ISSUE THREAD

**Issue by SigtryggurO** [LenFon/StronglyTypedId#5]
I think most of the features within this library have been supported since dotnet 6. 
At least that's when record structs where added too the language.
I don't see much in the way of also building for dotnet 6 and 7.

**Comment by LenFon** [comment]
Thank you for your suggestion. However, at this time, we are not considering support for .NET 6 in this project. This decision is due to certain interface features that are not supported in .NET 6.
